#!bin/bash

if [ $(uname) == Darwin ]; then
	if [ -f .bash_profile ]; then
		echo "You already have a bash profile" 
	else

	touch .bash_profile
	#Set CLICOLOR if you want ANSI colors in iTerm2	 
	echo "export CLICOLOR=1" >> .bash_profile
	# Set colors to match iTerm2 Terminal Colors
	echo "export TERM=xterm-256color" >> .bash_profile
	# Add android platform-toosl to path
	echo "export PATH=$PATH://Users/rohinpatel/Documents/android-sdk-macosx/platform-tools" >> .bash_profile
	#Set Default Editor 
	echo "export EDITOR=/usr/local/bin/vim" >> .bash_profile
	# Aliases
	echo "alias vim='/usr/local/bin/vim'" >> .bash_profile
	echo "alias rm='rm -i'" >> .bash_profile
	echo "alias cp='cp -i'" >> .bash_profile
	echo "alias ..='cd ../'" >> .bash_profile
	echo "alias ...='cd ../../'" >> .bash_profile
	echo "alias .3='cd ../../../'" >> .bash_profile

	fi
else
	if [ -f .bash_rc ]; then
		echo "You already have a bash profile" 
	else
	touch .bash_rc
	#Set CLICOLOR if you want ANSI colors in iTerm2	 
	echo "export CLICOLOR=1" >> .bash_rc
	# Set colors to match iTerm2 Terminal Colors
	echo "export TERM=xterm-256color" >> .bash_rc
	# Add android platform-toosl to path
	echo "export PATH=$PATH://Users/rohinpatel/Documents/android-sdk-macosx/platform-tools" >> .bash_rc
	#Set Default Editor 
	echo "export EDITOR=/usr/local/bin/vim" >> .bash_rc
	# Aliases
	echo "alias vim='/usr/local/bin/vim'" >> .bash_rc
	echo "alias rm='rm -i'" >> .bash_rc
	echo "alias cp='cp -i'" >> .bash_rc
	echo "alias ..='cd ../'" >> .bash_rc
	echo "alias ...='cd ../../'" >> .bash_rc
	echo "alias .3='cd ../../../'" >> .bash_rc
fi	
fi



		    



